### ISSUE TITLE
Write other language handlers

### ISSUE THREAD

**Issue by ngsankha** [ngsankha/judgev2#2]
They should go in `languages` folder. Take inspiration from `C.js`.
- [x] CPP
- [x] Java
- [x] Python

Give suggestions for more languages in the comments.

**Comment by ngsankha** [comment]
CPP and Python were added by #7.

**Comment by ngsankha** [comment]
Waiting for tests for CPP and Python from @aseemraj. After that we can close this. :)

**Comment by ngsankha** [comment]
I wrote the remaining tests and fixed a bug in the Python handler: b2234a096d0d98e961013f6d86a369121809d79e

**Comment by aseemrb** [comment]
Oh yes, I got to know what I missed there!
