### ISSUE TITLE
can not run on windows 7 64bit

### ISSUE THREAD

**Issue by tuanvayn** [ngsankha/judgev2#31]
when i run your code in my system. it show many bugs and a few package or plugin like fakechroot isnt support windows

**Comment by ngsankha** [comment]
This code is an experimental one and wasn't designed to run on Windows. This was developed keeping in mind only support for Linux.

That aside, this is being highly unstable may not be useful (but you can look at the code, there might be some useful things in there). I would recommend you to use [ngsankha/codejudge](https://github.com/ngsankha/codejudge) in case you are looking to setup a server to host programming contest.
