### ISSUE TITLE
Need an output checker

### ISSUE THREAD

**Issue by ngsankha** [ngsankha/judgev2#5]
The judge is useless without this. :trollface:

**Comment by arminvoid** [comment]
@sankha93 
More details?
Simply a program that compares two files and checks if they are exactly similar?
C/C++ would do?

**Comment by ngsankha** [comment]
Umm, they should check the strings rather than the files. No this has to be a part of the program and not an independent C, C++ program. The code should go [here](https://github.com/sankha93/judgev2/blob/master/slave.js#L123).

The basic algo would be something like:

```
if matchLines is false:
  check data == output:
    result is success
  else:
    result is failure
else:
  match each line of data with each line of output
  if it is not same and partial is false:
     result is failure
  else:
     result is the fraction of correct matches out of total number of lines
```
